name: Block Loot
main: com.pneumaticraft.blockloot.BlockLoot
authors: ['fernferret']
version: maven-version-number
commands:
  bl:
    description: Generic BlockLoot Command
    usage: /<command>
  blh:
    description: Generic BlockLoot Command
    usage: /<command>
  blhelp:
    description: Generic BlockLoot Command
    usage: /<command>
  blsearch:
    description: Generic BlockLoot Command
    usage: /<command>
